### ISSUE TITLE
Cracking the Coding Interview

### ISSUE THREAD

**Issue by RaymondFeckoury** [alpha037/data-structures-and-algorithms#6]
A folder containing the solutions to the data structures and algorithms problems in Cracking the Coding Interview. I think it may be useful for people testing their solutions. Since there are many approaches they can just copy/paste the solutions here and compare their code's behavior. Or, they can just reference solutions from here for better accessability (desk can get cramped with such a large book).
I am currently working my way through the book and can upload solutions as I go.

**Comment by alpha037** [comment]
Sure, that sounds like a great idea!
