### ISSUE TITLE
Algoexpert problem statements

### ISSUE THREAD

**Issue by Lucky-321** [alpha037/data-structures-and-algorithms#7]
You have added solutions to algoexpert problems but you haven't added any questions. could you please add them? I couldn't find questions anywhere. Questions refer to problem statement of questions.

**Comment by alpha037** [comment]
If I add them, then this repo could be taken down by the DMCA. :)

**Comment by Lucky-321** [comment]
> If I add them, then this repo could be taken down by the DMCA. :)
If you wish to share questions  personally( screenshots or pdfs). you can mail me at llakshmanmohan1@gmail.com. you can share them in a drive link if the total size of all questions is large. Thanks for the reply.
